# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-multiversion
SOURCEDIR     = source
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# from https://github.com/acerbilab/pyvbmc/blob/main/docsrc/Makefile
# copy example notebooks to source folder
# render docs
# copy rendered docs and .nojekyll (for github.io) to docs folder
# remove example notebooks from source folder
github:
# 	@cp ../INSTALL.rst source/installation.rst  # INSTALL.rst does not exist
	@cp ../CONTRIBUTING.md source/contributing.md
	@cp -a ../examples/. source/_examples
	@rm -rf source/_examples/in_progress  # ignore if in_progress does not exist
	@$(SPHINXBUILD) "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS)
	@echo 'Copying output from _build/html to ../docs.'
	@cp -a _build/html/. ../docs
	@cp .nojekyll ../docs/.nojekyll

clean:
	@rm -rf ../docs/*
	@rm -rf _build

clean-all:
	@rm -rf ../docs/*
	@rm -rf _build
	@rm -rf source/_examples
    # remove all files from source/api except for bayesflow.rst
	@find source/api -type f ! -name 'bayesflow.rst' -exec rm -f {} +

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
