name: Multi-Backend Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Multi-Backend Tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]
        backend: ["jax", "tensorflow", "torch"]

    runs-on: ${{ matrix.os }}

    env:
      KERAS_BACKEND: ${{ matrix.backend }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install .[test]

      - name: Install JAX
        if: ${{ matrix.backend == 'jax' }}
        run: |
          pip install -U jax

      - name: Install TensorFlow
        if: ${{ matrix.backend == 'tensorflow' }}
        run: |
          pip install -U tensorflow

      - name: Install PyTorch
        if: ${{ matrix.backend == 'torch' }}
        run: |
          pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Show Environment Info
        run: |
          python --version
          pip --version
          printenv | sort
          pip list

      # - name: Run Tests
      #   run: |
      #     pytest -x -m "not slow"

      - name: Run Slow Tests
        # Run slow tests on manual trigger and main. Limit to one OS and Python version.
        # Multiline if statements are weird, https://github.com/orgs/community/discussions/25641,
        # but feel free to convert it.
        if: ${{ ((github.event_name == 'workflow_dispatch') || (github.ref == 'main')) && ((matrix.os == 'windows-latest') && (matrix.python-version == '3.11')) }}
        run: |
          pytest -m "slow"
